apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true # avoid kubectl apply error metadata.annotations: Too long: must have at most 262144 bytes
  name: scaledobjects.keda.sh
