apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

helmCharts:
  - repo: https://kedacore.github.io/charts
    name: keda
    releaseName: keda
    namespace: keda
    valuesFile: values.yaml
